id: P1F3A55AB
initial_creation_type: input
source_metadata:
  title: Gompa Tsultrim Nyingpo Series
  language: bo
  description: 'Texts by and about Gompa Tsultrim Nyingpo (sgom pa tshul khrims snying
    po, 1116–1169), the eldest nephew of Gampopa:'
  volume:
    49594f62ff544848af87c8ec300979c2:
      title: A Brief Commentary on the Twelve Stanzas (Including the Divisions of
        the Stages of the Path for Individuals of the Three Capacities)
      parent: Lamrim
created_at: '2022-02-28T23:24:25.131381'
last_modified_at: '2022-02-28T23:24:25.131385'
statistics:
  total_words: 708
  total_non_words: 64
quality:
  non_words_ratio: 0.09
